### ISSUE TITLE
Gallery page : W3C erors

### ISSUE THREAD

**Issue by mahender-sowedane** [titan-cebu/Unison-Kitchens#55]
![2016-04-04_1730](https://cloud.githubusercontent.com/assets/13309730/14281013/1a01b3cc-fb54-11e5-9de6-ccab4fc64d6c.png)

**Comment by Rahul-titan** [comment]
As the short-code for the gallery is being wrapped in p tags by the wysiwyg editor, which cannot be deleted / unwrapped.
